-- Add missing columns to the posts table
ALTER TABLE posts ADD COLUMN IF NOT EXISTS author TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS is_saved BOOLEAN DEFAULT FALSE;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS is_saved_reddit BOOLEAN DEFAULT FALSE;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS reddit_url TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS original_title TEXT;
ALTER TABLE posts ADD COLUMN IF NOT EXISTS post_type TEXT DEFAULT 'community'; 