name: petform
description: Your comprehensive pet management companion. Track health, get AI advice, shop for supplies, and connect with the pet community.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.3
  http: ^1.4.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.1
  path_provider: ^2.1.1
  # NEW: Supabase
  supabase_flutter: ^2.8.0
  # REMOVE: Firebase (after migration)
  # firebase_core: ^3.14.0
  # firebase_auth: ^5.3.3
  # REMOVE: Hive (after migration)
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0
  video_player: ^2.8.1
  app_links: ^3.4.5
  flutter_secure_storage: ^9.2.4
  auth0_flutter: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  # REMOVE: Hive generators (after migration)
  # hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/appstore.png
    - lib/assets/animation2.mp4
    - lib/assets/petform_backdrop.png
    - lib/assets/animation.mp4
    - lib/assets/reddit.png

# Add flutter_launcher_icons for app icon generation
flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/appstore.png"


