name: petform
description: A pet management app.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.10  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true