name: petform
description: Your comprehensive pet management companion. Track health, get AI advice, shop for supplies, and connect with the pet community.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.0
  shimmer: ^2.0.0
  url_launcher: ^6.0.3
  http: ^1.4.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.3.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/reddit.png
    - lib/assets/petform_backdrop.png


