
import 'shopping_item.dart';
import 'tracking_metric.dart';

class Pet {
  final String? id;
  final String name;
  final String species;
  final String? breed;
  final int? age;
  final String? personality;
  final String? foodSource;
  final String? favoritePark;
  final String? leashSource;
  final String? litterType;
  final String? waterProducts;
  final String? tankSize;
  final String? cageSize;
  final String? favoriteToy;
  final String? photoUrl;
  final Map<String, dynamic>? customFields;
  final List<ShoppingItem> shoppingList;
  final List<TrackingMetric> trackingMetrics;

  Pet({
    this.id,
    required this.name,
    required this.species,
    this.breed,
    this.age,
    this.personality,
    this.foodSource,
    this.favoritePark,
    this.leashSource,
    this.litterType,
    this.waterProducts,
    this.tankSize,
    this.cageSize,
    this.favoriteToy,
    this.photoUrl,
    this.customFields,
    this.shoppingList = const [],
    this.trackingMetrics = const [],
  }) : assert(name.isNotEmpty, 'Pet name cannot be empty'),
       assert(species.isNotEmpty, 'Pet species cannot be empty');

  Pet copyWith({
    String? id,
    String? name,
    String? species,
    String? breed,
    int? age,
    String? personality,
    String? foodSource,
    String? favoritePark,
    String? leashSource,
    String? litterType,
    String? waterProducts,
    String? tankSize,
    String? cageSize,
    String? favoriteToy,
    String? photoUrl,
    Map<String, dynamic>? customFields,
    List<ShoppingItem>? shoppingList,
    List<TrackingMetric>? trackingMetrics,
  }) {
    return Pet(
      id: id ?? this.id,
      name: name ?? this.name,
      species: species ?? this.species,
      breed: breed ?? this.breed,
      age: age ?? this.age,
      personality: personality ?? this.personality,
      foodSource: foodSource ?? this.foodSource,
      favoritePark: favoritePark ?? this.favoritePark,
      leashSource: leashSource ?? this.leashSource,
      litterType: litterType ?? this.litterType,
      waterProducts: waterProducts ?? this.waterProducts,
      tankSize: tankSize ?? this.tankSize,
      cageSize: cageSize ?? this.cageSize,
      favoriteToy: favoriteToy ?? this.favoriteToy,
      photoUrl: photoUrl ?? this.photoUrl,
      customFields: customFields ?? this.customFields,
      shoppingList: shoppingList ?? this.shoppingList,
      trackingMetrics: trackingMetrics ?? this.trackingMetrics,
    );
  }

  factory Pet.fromJson(Map<String, dynamic> json) {
    return Pet(
      id: json['id'] as String?,
      name: json['name'] as String? ?? '', // Handle null case
      species: json['type'] as String? ?? '', // Handle null case
      breed: json['breed'] as String?,
      age: json['age'] as int?,
      personality: json['personality'] as String?,
      foodSource: json['foodsource'] as String?, // Note: lowercase from database
      favoritePark: json['favoritepark'] as String?, // Note: lowercase from database
      leashSource: json['leashsource'] as String?, // Note: lowercase from database
      litterType: json['littertype'] as String?, // Note: lowercase from database
      waterProducts: json['waterproducts'] as String?, // Note: lowercase from database
      tankSize: json['tanksize'] as String?, // Note: lowercase from database
      cageSize: json['cagesize'] as String?, // Note: lowercase from database
      favoriteToy: json['favoritetoy'] as String?, // Note: lowercase from database
      photoUrl: json['photourl'] as String?, // Note: lowercase from database
      customFields: Map<String, dynamic>.from(json['customfields'] ?? {}), // Note: lowercase from database
      shoppingList: (json['shoppingList'] as List<dynamic>?)
              ?.map((item) => ShoppingItem.fromJson(item))
              .toList() ??
          [],
      trackingMetrics: (json['trackingMetrics'] as List<dynamic>?)
              ?.map((metric) => TrackingMetric.fromJson(metric))
              .toList() ??
          [],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      // 'id': id, // Remove id since it should be auto-generated by Supabase
      'name': name,
      'type': species, // Note: database uses 'type' not 'species'
      'breed': breed,
      'age': age,
      'personality': personality,
      'foodsource': foodSource, // Note: lowercase in database
      'favoritepark': favoritePark, // Note: lowercase in database
      'leashsource': leashSource, // Note: lowercase in database
      'littertype': litterType, // Note: lowercase in database
      'waterproducts': waterProducts, // Note: lowercase in database
      'tanksize': tankSize, // Note: lowercase in database
      'cagesize': cageSize, // Note: lowercase in database
      'favoritetoy': favoriteToy, // Note: lowercase in database
      'photourl': photoUrl, // Note: lowercase in database
      'customfields': customFields, // Note: lowercase in database
      // Removed shoppingList and trackingMetrics since they don't exist as database columns
      // These are handled separately in their own tables
    };
  }
}
