// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBscaZVGjktbhKDtI4rTxM5bkuAe02w1SM',
    appId: '1:248552661178:web:your-web-app-id-here',
    messagingSenderId: '248552661178',
    projectId: 'petform-c4058',
    authDomain: 'petform-c4058.firebaseapp.com',
    storageBucket: 'petform-c4058.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBscaZVGjktbhKDtI4rTxM5bkuAe02w1SM',
    appId: '1:248552661178:android:your-android-app-id-here',
    messagingSenderId: '248552661178',
    projectId: 'petform-c4058',
    storageBucket: 'petform-c4058.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBscaZVGjktbhKDtI4rTxM5bkuAe02w1SM',
    appId: '1:248552661178:ios:ae2fc8f150e0dd95f1a283',
    messagingSenderId: '248552661178',
    projectId: 'petform-c4058',
    storageBucket: 'petform-c4058.firebasestorage.app',
    iosBundleId: 'com.waleedraza.petform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBscaZVGjktbhKDtI4rTxM5bkuAe02w1SM',
    appId: '1:248552661178:ios:ae2fc8f150e0dd95f1a283',
    messagingSenderId: '248552661178',
    projectId: 'petform-c4058',
    storageBucket: 'petform-c4058.firebasestorage.app',
    iosBundleId: 'com.waleedraza.petform',
  );
} 